### ISSUE TITLE
SocketException: 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by dreamCirno** [GEEKiDoS/NeteaseMuiscApi#2]
SocketException: 由于目标计算机积极拒绝，无法连接。

System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) (at <3649452ae23840d49bd323a708498f78>:0)
System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) (at <3649452ae23840d49bd323a708498f78>:0)
Rethrow as WebException: Error: ConnectFailure (由于目标计算机积极拒绝，无法连接。
)
System.Net.WebClient.UploadValues (System.Uri address, System.String method, System.Collections.Specialized.NameValueCollection data) (at <3649452ae23840d49bd323a708498f78>:0)
System.Net.WebClient.UploadValues (System.String address, System.String method, System.Collections.Specialized.NameValueCollection data) (at <3649452ae23840d49bd323a708498f78>:0)
(wrapper remoting-invoke-with-check) System.Net.WebClient:UploadValues (string,string,System.Collections.Specialized.NameValueCollection)
NeteaseCloudMusicApi.NeteaseMusicAPI.CURL (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] parms, System.String method) (at Assets/Scripts/NeteaseCloudMusicApi.cs:124)
NeteaseCloudMusicApi.NeteaseMusicAPI.Search (System.String keyword, System.Int32 limit, System.Int32 offset, NeteaseCloudMusicApi.NeteaseMusicAPI+SearchType type) (at Assets/Scripts/NeteaseCloudMusicApi.cs:162)
APIManager.SerachKeyword (System.String keyword, System.Int32 limit, System.Int32 offset) (at Assets/Scripts/APIManager.cs:35)
SearchManager.TotalKeyword () (at Assets/Scripts/SearchManager.cs:31)
SearchManager.SearchKeyword () (at Assets/Scripts/SearchManager.cs:22)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:165)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:36)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:45)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by GEEKiDoS** [comment]
我觉得是你自己的网络问题
建议套try catch
